### ISSUE TITLE
Fail file if it has fields that are not part of the schema

### ISSUE THREAD

**Issue by dvillaveces-tq** [CMSgov/hpt-validator#52]
## Issue Report

Some files contain "extra" fields that are not defined in the schema. These files are arguably not 100% compliant. 

### Expected behavior

Files with extra fields return an error.

### Actual behavior

Files with extra fields produce no errors and no warnings.

### Steps to reproduce the behavior

Here is an example:

- https://www.mskcc.org/teaser/standard-charges-nyc.json
    - Has extra field `hospital_professional`

1. Download file above
2. Pass it to the CLI validator (or web validator), no errors/warnings are returned
3. Open .json file and search for `hospital_professional`

**Comment by CarlsonErin** [comment]
In the 2024 OPPS/ASC final rule CMS permits hospitals to add additional contextual data elements in the CMS template layout.
