### ISSUE TITLE
hpt-validator does not validate any version 2.2 MRFs

### ISSUE THREAD

**Issue by michaelhjung** [CMSgov/hpt-validator#54]
## Issue Report

hpt-validator does not validate any version 2.2 MRFs

### Expected behavior

Should validate version 2.2 MRFs

### Actual behavior

The hpt-validator npm package is only validating for versions 1.1 and 2.0 - any MRFs with version "2.2" is failing. When changing the version indicated in that MRF from "2.2" to "2.0" and all other data is kept the same, it passes.

The [online validator](https://cmsgov.github.io/hpt-tool/online-validator/), however, is validating for version 2.2 MRFs successfully.

### Steps to reproduce the behavior

You can use the attached json as an example to pass into the validateJson function imported from hpt-validator. I convert the json to a readableStream to pass it in as the first argument, and use "2.2" for the 2nd argument

[example-hospital.json](https://github.com/user-attachments/files/16700692/example-hospital.json)

Thanks so much for your help!

**Comment by daniel-eckel** [comment]
Thank you for your comment. You're correct in that the CLI only accepts v2.0 and v2.0.0 options, but the validator technically evaluates any v2.0 files against all minor versions included in v2.0.  The minor versions of v2.0 may generate "warnings" vs "errors" depending on implementation date for various attributes. Those warnings will turn into errors on January 1, 2025.

**Comment by michaelhjung** [comment]
Hey thanks for the response Daniel. It looks like on the **online validator** (**hpt-tool** package), it hard-codes "v2.0" in the state, which is why any machine readable files with version: "2.2" may still pass (screenshot of the code below).

![Screenshot 2024-08-23 at 9 29 40 AM](https://github.com/user-attachments/assets/1aa753e6-e149-4ad2-9d5d-2e7fe7274d78)


However, when actually passing in "v2.2" in the validateJson function imported from the **hpt-validator** package it will fail no matter what because the logic only accounts for the arguments: "v1.1", "v2.0", and "v2.0.0" (see screenshot below).

![Screenshot 2024-08-23 at 9 34 51 AM](https://github.com/user-attachments/assets/7edecc6b-1028-4ba4-bbca-2ab002e1a3fa)


May we please keep this issue open until it is resolved? I can try to create a PR on my end to create the version 2.2 logic.

**Comment by michaelhjung** [comment]
@daniel-eckel 
For further context, in the online validator (hpt-tool), it never references the uploaded file's stated version. 

The initial state references the default hardcoded "v2.0" and once it has been processed it will again save that "v2.0" in sessionStorage - thus `file.version` is never used.

![Screenshot 2024-08-23 at 9 42 28 AM](https://github.com/user-attachments/assets/d9f0c64a-5b1c-4624-afbe-0e069ea846a9)

Both of the hpt-tool and hpt-validator packages will need fixes.

**Comment by daniel-eckel** [comment]
Currently, the online validator and CLI validator do not allow the user to specify a specific schema to test against. All files are effectively tested against the V2.2.0 logic with the requirements beginning July 1, 2024 producing "errors" and requirements beginning January 1, 2025 producing "warnings".
