### ISSUE TITLE
Add build that creates dist js file

### ISSUE THREAD

**Issue by danflanagan8** [CMSgov/hpt-validator#62]
## Issue Report

Add a build script that creates dist js file

### Expected behavior

I want to be able to run a command that generates a js file that I can use in a webpage, not just the command line.

### Actual behavior

The build script converts typescript to js in a `/lib` directory. But there's no reasonable way to run the js in a browser due to all the `import` statements.

### Steps to reproduce the behavior

If I run the build and then try to load `index.js` like so `<script src="path/to/lib/index.js" type="module"/>`, I quickly run into errors related to the various `import` statements in the js. I started to make an importmap, but there are too many dependencies and it was going to be a total mess.

The closely related hpt-tool repo has a build script that basically does what I'm looking for.

https://github.com/CMSgov/hpt-tool/blob/main/package.json#L12

When I run that, there's a dist folder that's generated that has all the static files for the tools to work.

**Comment by danflanagan8** [comment]
For a little more context, I'm developing a Drupal module related to HPT requirements.

I've been researching how to integrate these validation tools directly into the module.

https://www.drupal.org/project/hospital_price_transparency/issues/3476534

**Comment by shaselton-usds** [comment]
Hi @danflanagan8 - thank you for your interest in extending the HPT Validator code base.

Currently there are no plans for the team to build additional ways for the validator to be deployed to the web outside what is already in place.

I would suggest piggy-backing off of the build script that you've already pointed out. Maybe you can alter it for your build process to support your Drupal requirements. 

Thanks again for your question and interest in the project.
